// <auto-generated />
namespace GeekQuiz.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20905")]
    public sealed partial class QuestionHintLength : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(QuestionHintLength));
        
        string IMigrationMetadata.Id
        {
            get { return "201309232026541_QuestionHintLength"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
